### ISSUE TITLE
$ eval "$(ssh-agent -s)" > Agent pid 59566

### ISSUE THREAD

**Issue by canadianfarmer13** [wwalker/ssh-find-agent#30]

**Comment by wwalker** [comment]
@canadianfarmer13 

I assume you are saying I can just start another ssh-agent and import it into my local environment.

If you only use a couple of machines, that works well but on a daily basis I log into ~50 - ~800 machines from 12 different bastion hosts....

But, I usually have a previous agent (that I did start via ```eval $(ssh-agent -s)```) that I can use.
Likely that I just created a new agent in a different terminal, or a different window in tmux.

so, to reuse that agent, on most any platform, with minimal effort, I use ```ssh-find-agent``` 

E.g.:

I ssh to another machine, which  has an ssh-agent running, with my keys loaded in that agent.
- (for that machine, different from the keys on my local machine, so I won't be using ssh -A)

I don't want to have to enter all my passphrases again on that machine.

```
eval $(ssh-find-agent)
```
Now all my keys on the remote machine are available to me.  Instead of :
```
eval "$(ssh-agent -s)"
ssh-add
# hand enter long passphrases
```

**Comment by wwalker** [comment]
Reopen if this doesn't resolve your issue.
